// Shared helper: pull the TRIP object out of a trip's index.html.
//
// The TRIP block is plain data between two markers, so it can be read without
// a browser. Everything that needs the content at build time (meta sync,
// validation) goes through here, which keeps index.html the single source of
// truth. No separate JSON file to drift out of step.

import { readFileSync } from 'node:fs';
import vm from 'node:vm';

export const DATA_START = '/* ===========================================================================\n   TRIP:DATA:START';
export const META_START = '<!-- TRIP:META:START';
export const META_END = '<!-- TRIP:META:END -->';

export function readTrip(file) {
  const html = readFileSync(file, 'utf8');

  // Anchor on the declaration rather than on the markers alone: the prose
  // inside the block's own comment mentions both marker names, so searching
  // for the end marker from the top of the file lands in the wrong place.
  const startIdx = html.indexOf('TRIP:DATA:START');
  if (startIdx === -1) throw new Error(`${file}: could not find the TRIP:DATA:START marker`);

  const constIdx = html.indexOf('const TRIP', startIdx);
  if (constIdx === -1) throw new Error(`${file}: no "const TRIP" after the TRIP:DATA:START marker`);

  const endIdx = html.indexOf('TRIP:DATA:END', constIdx);
  if (endIdx === -1) throw new Error(`${file}: could not find the TRIP:DATA:END marker after the data`);

  // The end marker opens its own comment, so drop a dangling "/*".
  const source = html.slice(constIdx, endIdx).replace(/\/\*[^*]*$/, '');
  let trip;
  try {
    trip = vm.runInNewContext(`${source}\nTRIP;`, Object.create(null), { timeout: 2000 });
  } catch (err) {
    throw new Error(`${file}: the TRIP block is not valid JavaScript — ${err.message}`);
  }
  return { trip, html };
}

export function renderMeta(trip) {
  const url = trip.url.endsWith('/') ? trip.url : trip.url + '/';
  const img = url + 'og-cover.jpg';
  const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');

  return [
    `${META_START}  generated by tools/sync-meta.mjs, do not hand-edit -->`,
    `<title>${esc(trip.title)}</title>`,
    `<meta name="description" content="${esc(trip.share.description)}">`,
    `<meta property="og:type" content="website">`,
    `<meta property="og:url" content="${esc(url)}">`,
    `<meta property="og:title" content="${esc(trip.share.title)}">`,
    `<meta property="og:description" content="${esc(trip.share.description)}">`,
    `<meta property="og:image" content="${esc(img)}">`,
    `<meta property="og:image:type" content="image/jpeg">`,
    `<meta property="og:image:width" content="1200">`,
    `<meta property="og:image:height" content="630">`,
    `<meta property="og:image:alt" content="${esc(trip.share.imageAlt)}">`,
    `<meta name="twitter:card" content="summary_large_image">`,
    `<meta name="twitter:title" content="${esc(trip.share.title)}">`,
    `<meta name="twitter:description" content="${esc(trip.share.description)}">`,
    `<meta name="twitter:image" content="${esc(img)}">`,
    META_END
  ].join('\n');
}

export function replaceMeta(html, block) {
  const start = html.indexOf(META_START);
  const end = html.indexOf(META_END);
  if (start === -1 || end === -1) {
    throw new Error('could not find the TRIP:META:START / TRIP:META:END markers');
  }
  return html.slice(0, start) + block + html.slice(end + META_END.length);
}

export function currentMeta(html) {
  const start = html.indexOf(META_START);
  const end = html.indexOf(META_END);
  if (start === -1 || end === -1) return null;
  return html.slice(start, end + META_END.length);
}
